# docker-compose.yml

version: '3.8' # 指定 docker-compose 文件版本

services:
  # 定义一个名为 'db' 的服务
  db:
    image: postgres:15 # 使用官方的 PostgreSQL 15 镜像
    container_name: language_db_container # 给容器起一个好记的名字
    restart: always # 如果容器挂了，自动重启
    environment:
      POSTGRES_USER: sky # 设置数据库用户名
      POSTGRES_PASSWORD: 9okmMKO( # 设置数据库密码
      POSTGRES_DB: dutch_app_db # 设置数据库名称
    ports:
      - "5432:5432" # 将你电脑的 5432 端口映射到容器的 5432 端口
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 将数据库数据持久化到本地
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sky -d dutch_app_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
